# Generated by Django 4.1.7 on 2023-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
