# Generated by Django 4.1.7 on 2023-05-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0002_alter_registro_contra_alter_registro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
    ]
