# Generated by Django 4.1.7 on 2023-05-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0003_remove_registro_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
